#!/usr/bin/env python3
"""Convert reference materials (PDF, PPTX, DOCX) to markdown.

Usage:
    python -m scripts.convert_references reference/
    python -m scripts.convert_references reference/ --pdf-backend mineru

Converts all supported files in the given directory to .md files
in the same directory. Skips files that already have a .md counterpart.

PDF conversion uses PyMuPDF by default. Use ``--pdf-backend mineru``
when the MinerU CLI is installed and OCR/layout-aware extraction is preferred.

Dependencies (install via: uv sync):
    - pymupdf (fitz)  — default PDF extraction
    - python-pptx     — PowerPoint extraction
    - python-docx     — Word document extraction

Optional dependency:
    - mineru CLI      — OCR/layout-aware PDF extraction with --pdf-backend mineru
    - six             — MinerU pipeline compatibility import for current releases
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlsplit


PDF_BACKENDS = ("pymupdf", "mineru")
MINERU_BACKENDS = (
    "pipeline",
    "vlm-engine",
    "hybrid-engine",
    "vlm-http-client",
    "hybrid-http-client",
)
MINERU_METHODS = ("auto", "txt", "ocr")
MARKDOWN_LINK_RE = re.compile(r"(!?\[[^\]]*\]\()([^)]+)(\))")


def convert_pdf_with_pymupdf(path: Path) -> str:
    """Extract text from PDF using PyMuPDF."""
    import fitz

    doc = fitz.open(path)
    parts = []
    for i, page in enumerate(doc, 1):
        text = page.get_text()
        if text.strip():
            parts.append(f"<!-- Page {i} -->\n\n{text.strip()}")
    doc.close()
    return "\n\n---\n\n".join(parts)


def find_mineru_markdown(output_dir: Path, source_path: Path) -> Path:
    """Find the primary markdown file generated by MinerU."""
    candidates = [p for p in output_dir.rglob("*.md") if p.is_file()]
    if not candidates:
        raise FileNotFoundError("MinerU completed but did not produce a markdown file")

    exact_matches = [p for p in candidates if p.name == f"{source_path.stem}.md"]
    if exact_matches:
        return sorted(exact_matches, key=lambda p: (len(p.parts), str(p)))[0]

    return max(candidates, key=lambda p: (p.stat().st_size, str(p)))


def _is_relative_to(path: Path, base: Path) -> bool:
    """Return whether path is inside base, compatible with Python 3.10."""
    try:
        path.relative_to(base)
    except ValueError:
        return False
    return True


def preserve_mineru_assets(markdown: str, md_path: Path, out_path: Path) -> str:
    """Copy MinerU-generated local assets next to the final markdown file."""
    source_root = md_path.parent.resolve()
    asset_dir = out_path.parent / f"{out_path.stem}_assets"

    def replace_link(match: re.Match[str]) -> str:
        label, raw_target, suffix = match.groups()
        target = raw_target.strip()
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc or target.startswith("#"):
            return match.group(0)

        raw_path = parsed.path
        if not raw_path:
            return match.group(0)

        rel_path = Path(unquote(raw_path))
        if rel_path.is_absolute() or ".." in rel_path.parts:
            return match.group(0)

        source_path = (source_root / rel_path).resolve()
        if not _is_relative_to(source_path, source_root) or not source_path.is_file():
            return match.group(0)

        destination = asset_dir / rel_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination)

        query = f"?{parsed.query}" if parsed.query else ""
        fragment = f"#{parsed.fragment}" if parsed.fragment else ""
        rewritten = f"{asset_dir.name}/{rel_path.as_posix()}{query}{fragment}"
        return f"{label}{rewritten}{suffix}"

    return MARKDOWN_LINK_RE.sub(replace_link, markdown)


def convert_pdf_with_mineru(path: Path, out_path: Path, args: argparse.Namespace) -> str:
    """Extract markdown from PDF using the MinerU CLI."""
    if shutil.which("mineru") is None:
        raise RuntimeError(
            "MinerU CLI not found. Install it first, for example: "
            'uv pip install -U "mineru[pipeline]" six'
        )

    with tempfile.TemporaryDirectory(prefix="tdaa-mineru-") as tmpdir:
        output_dir = Path(tmpdir) / "output"
        command = [
            "mineru",
            "-p",
            str(path),
            "-o",
            str(output_dir),
            "-b",
            args.mineru_backend,
            "-m",
            args.mineru_method,
        ]
        if args.mineru_lang:
            command.extend(["-l", args.mineru_lang])
        if args.mineru_api_url:
            command.extend(["--api-url", args.mineru_api_url])
        if args.mineru_url:
            command.extend(["-u", args.mineru_url])
        if args.mineru_effort:
            command.extend(["--effort", args.mineru_effort])
        command.extend(args.mineru_arg)

        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            details = [f"MinerU failed with exit code {result.returncode}."]
            if result.stdout.strip():
                details.append(f"stdout:\n{result.stdout.strip()}")
            if result.stderr.strip():
                details.append(f"stderr:\n{result.stderr.strip()}")
            raise RuntimeError("\n".join(details))

        md_path = find_mineru_markdown(output_dir, path)
        content = md_path.read_text(encoding="utf-8", errors="replace").strip()
        if not content:
            raise RuntimeError(f"MinerU produced an empty markdown file: {md_path}")
        return preserve_mineru_assets(content, md_path, out_path)


def convert_pptx(path: Path) -> str:
    """Extract text from PowerPoint slides."""
    from pptx import Presentation

    prs = Presentation(path)
    parts = []
    for i, slide in enumerate(prs.slides, 1):
        texts = []
        for shape in slide.shapes:
            if shape.has_text_frame:
                for para in shape.text_frame.paragraphs:
                    line = para.text.strip()
                    if line:
                        texts.append(line)
            if shape.has_table:
                table = shape.table
                for row in table.rows:
                    cells = [cell.text.strip() for cell in row.cells]
                    texts.append("| " + " | ".join(cells) + " |")
        if texts:
            slide_title = texts[0]
            body = "\n\n".join(texts[1:]) if len(texts) > 1 else ""
            parts.append(f"## Slide {i}: {slide_title}\n\n{body}")
    return "\n\n---\n\n".join(parts)


def convert_docx(path: Path) -> str:
    """Extract text from Word document."""
    from docx import Document

    doc = Document(path)
    parts = []
    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue
        style = para.style.name.lower() if para.style else ""
        if "heading 1" in style:
            parts.append(f"# {text}")
        elif "heading 2" in style:
            parts.append(f"## {text}")
        elif "heading 3" in style:
            parts.append(f"### {text}")
        else:
            parts.append(text)

    # Extract tables
    for table in doc.tables:
        rows = []
        for row in table.rows:
            cells = [cell.text.strip() for cell in row.cells]
            rows.append("| " + " | ".join(cells) + " |")
        if rows:
            # Add header separator after first row
            num_cols = len(table.rows[0].cells)
            header_sep = "| " + " | ".join(["---"] * num_cols) + " |"
            rows.insert(1, header_sep)
            parts.append("\n".join(rows))

    return "\n\n".join(parts)


CONVERTERS = {
    ".pptx": convert_pptx,
    ".ppt": convert_pptx,  # python-pptx only supports .pptx; will error on old .ppt
    ".docx": convert_docx,
    ".doc": convert_docx,  # python-docx only supports .docx; will error on old .doc
}
SUPPORTED_EXTENSIONS = {".pdf", *CONVERTERS}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", help="Directory containing reference materials")
    parser.add_argument(
        "--pdf-backend",
        choices=PDF_BACKENDS,
        default="pymupdf",
        help="PDF conversion backend (default: %(default)s)",
    )
    parser.add_argument(
        "--mineru-backend",
        choices=MINERU_BACKENDS,
        default="pipeline",
        help="MinerU parsing backend used when --pdf-backend mineru is set (default: %(default)s)",
    )
    parser.add_argument(
        "--mineru-method",
        choices=MINERU_METHODS,
        default="auto",
        help="MinerU parsing method used when --pdf-backend mineru is set (default: %(default)s)",
    )
    parser.add_argument(
        "--mineru-lang",
        help="Document language passed to MinerU OCR, for example 'en' or 'ch'",
    )
    parser.add_argument(
        "--mineru-api-url",
        help="Existing MinerU FastAPI base URL; omitted means MinerU starts a temporary local API",
    )
    parser.add_argument(
        "--mineru-url",
        help="OpenAI-compatible backend URL for MinerU http-client backends",
    )
    parser.add_argument(
        "--mineru-effort",
        choices=("medium", "high"),
        help="Hybrid parsing effort passed to MinerU when using a hybrid backend",
    )
    parser.add_argument(
        "--mineru-arg",
        action="append",
        default=[],
        help="Additional raw argument passed to MinerU; repeat as needed (use --mineru-arg=--flag=value)",
    )
    return parser.parse_args(argv)


def convert_file(path: Path, out_path: Path, args: argparse.Namespace) -> str:
    """Convert a supported source file to markdown content."""
    if path.suffix.lower() == ".pdf":
        if args.pdf_backend == "mineru":
            return convert_pdf_with_mineru(path, out_path, args)
        return convert_pdf_with_pymupdf(path)

    converter = CONVERTERS[path.suffix.lower()]
    return converter(path)


def main(argv: list[str] | None = None):
    args = parse_args(argv)
    ref_dir = Path(args.directory)
    if not ref_dir.is_dir():
        print(f"Error: {ref_dir} is not a directory")
        sys.exit(1)

    files = sorted(ref_dir.iterdir())
    converted = 0
    skipped = 0
    errors = []

    for f in files:
        if f.suffix.lower() not in SUPPORTED_EXTENSIONS:
            continue

        out_path = f.with_suffix(".md")
        if out_path.exists():
            print(f"  skip (exists): {out_path.name}")
            skipped += 1
            continue

        print(f"  converting: {f.name} -> {out_path.name}")
        try:
            md_content = convert_file(f, out_path, args)
            header = f"# {f.stem}\n\n> Converted from `{f.name}`\n\n"
            out_path.write_text(header + md_content, encoding="utf-8")
            converted += 1
        except Exception as e:
            errors.append((f.name, str(e)))
            print(f"  ERROR: {f.name}: {e}")

    print(f"\nDone: {converted} converted, {skipped} skipped, {len(errors)} errors")
    if errors:
        print("\nErrors:")
        for name, err in errors:
            print(f"  {name}: {err}")
        sys.exit(1)


if __name__ == "__main__":
    main()
